In [1]:
###### Set Up #####
# verify our folder with the data and module assets is installed
# if it is installed make sure it is the latest
!test -e ds-assets && cd ds-assets && git pull && cd ..
# if it is not installed clone it 
!test ! -e ds-assets && git clone https://github.com/IndraniMandal/ds-assets.git
# point to the folder with the assets
home = "ds-assets/assets/" 
import sys
sys.path.append(home)      # add home folder to module search path

Cloning into 'ds-assets'...
remote: Enumerating objects: 197, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 197 (delta 14), reused 30 (delta 13), pack-reused 164
Receiving objects: 100% (197/197), 10.34 MiB | 9.66 MiB/s, done.
Resolving deltas: 100% (74/74), done.

# Team Exercise

In this exercise we use a data set to predict cervical cancer risk based on social and behavior characteristics. You can use this template as the starting point of your analysis.

Do the following:

* Build a 1-hidden-layer MLP according to our rule of thumb and using the 'relu' activation function (train and test on full data set).
* Build a best 2-layer MLP using grid-search to search over layer sizes and activation functions.  For the activation functions use 'logistic' and 'relu'. For more details see the [MLP documentation](https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html).
* Build a best decision tree using grid-search for this data set.

Evaluation:
* Which one of the above models has the best accuracy?
* Are the differences in accuracy between the three models statistically significant?

## Dataset
The dataset in this template contains 19 attributes regarding behavior their relationship to cervical cancer risk. 
The associated academic paper with this data set can be found [here](https://www.researchgate.net/profile/Adi-Wijaya/publication/318009235_Behavior_determinant_based_cervical_cancer_early_detection_with_machine_learning_algorithm/links/5c185a414585157ac1ca13c6/Behavior-determinant-based-cervical-cancer-early-detection-with-machine-learning-algorithm.pdf).  [Homepage](https://archive.ics.uci.edu/ml/datasets/Cervical+Cancer+Behavior+Risk) for this data set.

The indepdent attributes are as follows:
1. behavior_sexualRisk (1-10)
1. behavior_eating (1-15)
1. behavior_personalHygine (1-15)
1. intention_aggregation (1-10)
1. intention_commitment (1-15)
1. attitude_consistency (1-10)
1. attitude_spontaneity (1-10)
1. norm_significantPerson (1-5)
1. norm_fulfillment (1-15)
1. perception_vulnerability (1-15)
1. perception_severity (1-10)
1. motivation_strength (1-15)
1. motivation_willingness (1-15)
1. socialSupport_emotionality (1-15)
1. socialSupport_appreciation (1-10)
1. socialSupport_instrumental (1-15)
1. empowerment_knowledge (1-15)
1. empowerment_abilities (1-15)
1. aempowerment_desires (1-15)

Dependent attribute:

ca_cervix (0 - low risk, 1 - high risk)

##Analysis

In [ ]:
import pandas as pd

In [ ]:
# get data
df = pd.read_csv(home+"sobar-72.csv")
df.head(n=10)

   behavior_sexualRisk  behavior_eating  ...  empowerment_desires  ca_cervix
0                   10               13  ...                    8          1
1                   10               11  ...                    4          1
2                   10               15  ...                   15          1
3                   10               11  ...                    4          1
4                    8               11  ...                    7          1
5                   10               14  ...                    6          1
6                   10               15  ...                    5          1
7                    8               12  ...                   12          1
8                   10               15  ...                   15          1
9                    7               15  ...                    4          1

[10 rows x 20 columns]